version: "2"

services:

  db:
    image: mdillon/postgis:9.4
    container_name: gps_collector_db
    environment:
      POSTGRES_DB: gps_collector
      POSTGRES_PASSWORD: gps_collector
      POSTGRES_USER: gps_collector
    ports:
      - "5434:5432"

  app:
    build: .
    ports:
      - "4567:4567"
    environment:
      DB_NAME: gps_collector
      DB_PASS: gps_collector
      DB_USER: gps_collector
      DB_PORT: 5432
      DB_HOST: db
    volumes:
      - ./:/app
    container_name: assignment
    command: ["./wait-for-it.sh", "db", "--", "./run.sh"]
    depends_on:
      - db

  
